/**
 * BM_NativeBridge.js
 * @NApiVersion 2.1
 * @NModuleScope SameAccount
 *
 * Integration bridge between this SuiteApp and NetSuite's native
 * "Match Bank Data" module (Transactions > Bank > Match Bank Data).
 *
 * ─── How the two systems work together ───────────────────────────────────────
 *
 *  PHASE 1 – Bank Match SuiteApp  (THIS APP)
 *  ──────────────────────────────────────────
 *  1. Import bank statement lines (CSV upload in this SuiteApp).
 *  2. Engine scores and proposes matches:
 *       credit  → Customer Payment applied to open Sales Invoice
 *       debit   → Vendor Payment confirmed (optionally date-adjusted)
 *  3. Approver reviews proposals and sets Status = Approved.
 *  4. Approval triggers BM_Proposal_UE → reconciliation applied in NetSuite:
 *       • Customer Payment record created (linked to invoice)
 *       • Vendor Payment trandate updated (if date-adjust checked)
 *  Result: proper NetSuite account transactions now exist.
 *
 *  PHASE 2 – NetSuite native Match Bank Data module
 *  ─────────────────────────────────────────────────
 *  1. User downloads the OFX file generated by this module and uploads it to
 *     Transactions > Bank > Banking Import History > Upload File.
 *     (OR the same CSV can be uploaded directly if OFX is not preferred.)
 *  2. On the Match Bank Data page the RIGHT panel shows our applied Customer
 *     Payments and Vendor Payments as account transactions.
 *  3. Intelligent Transaction Matching auto-matches many of them to the
 *     imported bank lines on the LEFT panel.
 *  4. User submits matches → Reconcile Account Statement → Done.
 *
 * ─── What this module provides ───────────────────────────────────────────────
 *  generateOFX(bankTxns)   – Converts our bank_txn records to OFX 1.02 SGML
 *                            format, importable by the native module.
 *  nativeModuleUrl()       – Returns the URL to open Match Bank Data.
 *  nativeImportUrl()       – Returns the URL to open Banking Import History.
 */
define(['N/search', 'N/log', './BM_Constants'], function (search, log, C) {
    'use strict';

    // ── OFX date formatter ────────────────────────────────────────────────
    // OFX format: YYYYMMDDHHMMSS  (NetSuite accepts YYYYMMDD too)
    function _ofxDate(dateStr) {
        if (!dateStr) return '19700101000000';
        var d = new Date(dateStr);
        if (isNaN(d.getTime())) return '19700101000000';
        var pad = function (n) { return String(n).padStart(2, '0'); };
        return String(d.getFullYear()) +
               pad(d.getMonth() + 1) +
               pad(d.getDate()) +
               '000000';
    }

    // ── OFX transaction type ──────────────────────────────────────────────
    // OFX types: CREDIT, DEBIT, INT, DIV, FEE, SRVCHG, DEP, ATM, POS, XFER, CHECK, PAYMENT, CASH
    function _ofxTrnType(amount) {
        return parseFloat(amount) >= 0 ? 'CREDIT' : 'DEBIT';
    }

    // ── Escape OFX text (basic) ───────────────────────────────────────────
    function _esc(s) {
        return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    /**
     * Generate an OFX 1.02 SGML file from an array of bank transaction objects.
     *
     * Each object should have: { date, description, amount, reference, currency }
     *
     * The resulting string can be written to a file and downloaded by the user.
     * They then upload it at: Transactions > Bank > Banking Import History > Upload File
     *
     * @param {Array}  bankTxns   Array of bank transaction data objects
     * @param {string} accountId  Bank account identifier (shown in OFX header)
     * @param {string} currency   Currency code, e.g. 'USD'
     * @returns {string}  OFX file content
     */
    function generateOFX(bankTxns, accountId, currency) {
        currency   = currency   || 'USD';
        accountId  = accountId  || 'CHECKING';

        var now     = _ofxDate(new Date().toISOString());
        var minDate = now;
        var maxDate = now;

        // Determine date range
        bankTxns.forEach(function (t) {
            var d = _ofxDate(t.date);
            if (d < minDate) minDate = d;
            if (d > maxDate) maxDate = d;
        });

        // Build transaction list
        var txnLines = bankTxns.map(function (t, idx) {
            var amt     = parseFloat(t.amount) || 0;
            var fitId   = t.reference || ('BM' + String(idx + 1).padStart(6, '0'));
            var name    = _esc(t.description || t.reference || 'Bank Transaction');
            var memo    = _esc(t.reference   || t.description || '');
            return [
                '<STMTTRN>',
                '<TRNTYPE>'  + _ofxTrnType(amt)            + '</TRNTYPE>',
                '<DTPOSTED>' + _ofxDate(t.date)            + '</DTPOSTED>',
                '<TRNAMT>'   + amt.toFixed(2)               + '</TRNAMT>',
                '<FITID>'    + _esc(fitId)                  + '</FITID>',
                '<NAME>'     + name                         + '</NAME>',
                '<MEMO>'     + memo                         + '</MEMO>',
                '</STMTTRN>'
            ].join('\n');
        }).join('\n');

        // Build full OFX 1.02 document
        var ofx = [
            'OFXHEADER:100',
            'DATA:OFXSGML',
            'VERSION:102',
            'SECURITY:NONE',
            'ENCODING:UTF-8',
            'CHARSET:1252',
            'COMPRESSION:NONE',
            'OLDFILEUID:NONE',
            'NEWFILEUID:NONE',
            '',
            '<OFX>',
            '<SIGNONMSGSRSV1>',
            '<SONRS>',
            '<STATUS><CODE>0</CODE><SEVERITY>INFO</SEVERITY></STATUS>',
            '<DTSERVER>' + now + '</DTSERVER>',
            '<LANGUAGE>ENG</LANGUAGE>',
            '</SONRS>',
            '</SIGNONMSGSRSV1>',
            '<BANKMSGSRSV1>',
            '<STMTTRNRS>',
            '<TRNUID>1001</TRNUID>',
            '<STMTRS>',
            '<CURDEF>' + _esc(currency) + '</CURDEF>',
            '<BANKACCTFROM>',
            '<BANKID>000000000</BANKID>',
            '<ACCTID>' + _esc(accountId) + '</ACCTID>',
            '<ACCTTYPE>CHECKING</ACCTTYPE>',
            '</BANKACCTFROM>',
            '<BANKTRANLIST>',
            '<DTSTART>' + minDate + '</DTSTART>',
            '<DTEND>'   + maxDate + '</DTEND>',
            txnLines,
            '</BANKTRANLIST>',
            '<LEDGERBAL>',
            '<BALAMT>0.00</BALAMT>',
            '<DTASOF>' + now + '</DTASOF>',
            '</LEDGERBAL>',
            '</STMTRS>',
            '</STMTTRNRS>',
            '</BANKMSGSRSV1>',
            '</OFX>'
        ].join('\n');

        return ofx;
    }

    /**
     * Load all unreconciled bank transaction records and return as plain objects.
     * @param {Array} statusFilter  Array of status codes, e.g. ['1','2']
     * @returns {Array}
     */
    function loadBankTxns(statusFilter) {
        var BTF = C.BANK_TXN_FIELDS;
        var filters = [['isinactive', 'is', 'F']];
        if (statusFilter && statusFilter.length) {
            filters.push('AND');
            filters.push([BTF.STATUS, 'anyof', statusFilter]);
        }
        var results = [];
        try {
            search.create({
                type: C.RECORDS.BANK_TXN,
                filters: filters,
                columns: [
                    BTF.TXN_DATE, BTF.DESCRIPTION,
                    BTF.AMOUNT,   BTF.REFERENCE,
                    BTF.CURRENCY, BTF.STATUS
                ]
            }).run().each(function (row) {
                results.push({
                    id:          row.id,
                    date:        row.getValue(BTF.TXN_DATE),
                    description: row.getValue(BTF.DESCRIPTION),
                    amount:      row.getValue(BTF.AMOUNT),
                    reference:   row.getValue(BTF.REFERENCE),
                    currency:    row.getValue(BTF.CURRENCY),
                    status:      row.getValue(BTF.STATUS)
                });
                return results.length < 500;
            });
        } catch (e) {
            log.error('BM_NativeBridge.loadBankTxns', e.message);
        }
        return results;
    }

    /**
     * Returns the path to NetSuite's native Match Bank Data page.
     * Optional accountId (internal ID of the bank account) pre-selects the account.
     */
    function nativeMatchBankDataUrl(accountId) {
        var base = '/app/accounting/transactions/bank/reconciliation/matchbankdata.nl';
        return accountId ? base + '?account=' + encodeURIComponent(accountId) : base;
    }

    /**
     * Returns the path to NetSuite's Banking Import History page (for OFX upload).
     */
    function nativeBankImportUrl() {
        return '/app/accounting/transactions/bank/reconciliation/bankingimporthistory.nl';
    }

    return {
        generateOFX:             generateOFX,
        loadBankTxns:            loadBankTxns,
        nativeMatchBankDataUrl:  nativeMatchBankDataUrl,
        nativeBankImportUrl:     nativeBankImportUrl
    };
});
